services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: smarthire
      POSTGRES_USER: smarthire
      POSTGRES_PASSWORD: smarthire
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  ml:
    build: ./ml_service
    ports:
      - "8001:8001"
    environment:
      - MODEL_NAME=all-mpnet-base-v2
    restart: on-failure

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smarthire
      SPRING_DATASOURCE_USERNAME: smarthire
      SPRING_DATASOURCE_PASSWORD: smarthire
      ML_SERVICE_URL: http://ml:8001
    depends_on:
      - postgres
      - ml

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - PROXY_TARGET=http://backend:8080
    depends_on:
      - backend

volumes:
  pgdata:
